/* 
 * Colosoft Framework - generic framework to assist in development on the .NET platform
 * Copyright (C) 2013  <http://www.colosoft.com.br/framework> - support@colosoft.com.br
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataEntryDownloaderServiceReference.IDataEntryDownloaderService")]
    internal interface IDataEntryDownloaderService {
        
        // CODEGEN: Generating message contract since the wrapper name (GetDataEntriesRequest) of message GetDataEntriesRequest does not match the default value (GetDataEntries)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataEntryDownloaderService/GetDataEntries", ReplyAction="http://tempuri.org/IDataEntryDownloaderService/GetDataEntriesResponse")]
        Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.DataEntryDownloaderContentInfo GetDataEntries(Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.GetDataEntriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataEntriesRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class GetDataEntriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Colosoft.Data.Caching.DataEntryVersion[] Versions;
        
        public GetDataEntriesRequest() {
        }
        
        public GetDataEntriesRequest(Colosoft.Data.Caching.DataEntryVersion[] Versions) {
            this.Versions = Versions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataEntryDownloaderContentInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class DataEntryDownloaderContentInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Data;
        
        public DataEntryDownloaderContentInfo() {
        }
        
        public DataEntryDownloaderContentInfo(long Length, string Name, System.IO.Stream Data) {
            this.Length = Length;
            this.Name = Name;
            this.Data = Data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IDataEntryDownloaderServiceChannel : Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.IDataEntryDownloaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class DataEntryDownloaderServiceClient : System.ServiceModel.ClientBase<Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.IDataEntryDownloaderService>, Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.IDataEntryDownloaderService {
        
        public DataEntryDownloaderServiceClient() {
        }
        
        public DataEntryDownloaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataEntryDownloaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataEntryDownloaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataEntryDownloaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.DataEntryDownloaderContentInfo Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.IDataEntryDownloaderService.GetDataEntries(Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.GetDataEntriesRequest request) {
            return base.Channel.GetDataEntries(request);
        }
        
        public long GetDataEntries(Colosoft.Data.Caching.DataEntryVersion[] Versions, out string Name, out System.IO.Stream Data) {
            Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.GetDataEntriesRequest inValue = new Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.GetDataEntriesRequest();
            inValue.Versions = Versions;
            Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.DataEntryDownloaderContentInfo retVal = ((Colosoft.Data.Caching.Remote.Client.DataEntryDownloaderServiceReference.IDataEntryDownloaderService)(this)).GetDataEntries(inValue);
            Name = retVal.Name;
            Data = retVal.Data;
            return retVal.Length;
        }
    }
}
