/* 
 * Colosoft Framework - generic framework to assist in development on the .NET platform
 * Copyright (C) 2013  <http://www.colosoft.com.br/framework> - support@colosoft.com.br
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colosoft.Security.Remote.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colosoft.Security.Remote.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor para recuperar o perfil..
        /// </summary>
        internal static string RemoteProfileProvider_GetProfileCommunicationError {
            get {
                return ResourceManager.GetString("RemoteProfileProvider_GetProfileCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema inesperado no servidor e não foi possível recuperar o perfil. 
        ///Detalhes: {0}.
        /// </summary>
        internal static string RemoteProfileProvider_GetProfileFaultException {
            get {
                return ResourceManager.GetString("RemoteProfileProvider_GetProfileFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor para recuperar os perfis do usuário. Endereço: {0}.
        /// </summary>
        internal static string RemoteProfileProvider_GetUserProfilesCommunicationError {
            get {
                return ResourceManager.GetString("RemoteProfileProvider_GetUserProfilesCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema inesperado no servidor e não foi possível recuperar os perfis do usuário. 
        ///Detalhes: {0}.
        /// </summary>
        internal static string RemoteProfileProvider_GetUserProfilesFaultException {
            get {
                return ResourceManager.GetString("RemoteProfileProvider_GetUserProfilesFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor para validar o token do usuário..
        /// </summary>
        internal static string RemoteTokenProvider_CheckTokenCommunicationError {
            get {
                return ResourceManager.GetString("RemoteTokenProvider_CheckTokenCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível acessar o endereço do servidor para realizar a validação
        ///do token de segurança. Verifica se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteTokenProvider_CheckTokenEndpointNotFound {
            get {
                return ResourceManager.GetString("RemoteTokenProvider_CheckTokenEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema inesperado no servidor de autenticação e não foi possível validar o token do usuário. 
        ///Detalhes: {0}.
        /// </summary>
        internal static string RemoteTokenProvider_CheckTokenFaultException {
            get {
                return ResourceManager.GetString("RemoteTokenProvider_CheckTokenFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido na validação do token..
        /// </summary>
        internal static string RemoteTokenProvider_CheckTokenUnknownError {
            get {
                return ResourceManager.GetString("RemoteTokenProvider_CheckTokenUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível acessar o endereço do servidor para realizar a validação
        ///do token de segurança. Verifica se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteUserProvider_ValidateTokenErrorEndpointNotFound {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateTokenErrorEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor de autenticação.
        ///Verifique se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteUserProvider_ValidateTokenErrorInCommunication {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateTokenErrorInCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor de autenticação. O tempo limite para acesso expirou. 
        ///Verifique se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteUserProvider_ValidateTokenErrorInCommunicationTimeout {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateTokenErrorInCommunicationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema inesperado no servidor de autenticação e não foi possível validar o token..
        /// </summary>
        internal static string RemoteUserProvider_ValidateTokenFaultException {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateTokenFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido na autenticação e não foi possível validar o token.
        ///Error: {0}.
        /// </summary>
        internal static string RemoteUserProvider_ValidateTokenUnknownError {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateTokenUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível acessar o endereço do servidor de autenticação.
        ///Verifica se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteUserProvider_ValidateUserErrorEndpointNotFound {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateUserErrorEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor de autenticação. Verifique se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteUserProvider_ValidateUserErrorInCommunication {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateUserErrorInCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com o servidor de autenticação. O tempo limite para acesso expirou. 
        ///Verifique se a rede está ativa e tente novamente..
        /// </summary>
        internal static string RemoteUserProvider_ValidateUserErrorInCommunicationTimeout {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateUserErrorInCommunicationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema inexperado no servidor de autenticação e não foi possível validar o usuário. 
        ///Verifique se o servidor de autenticação está executando corretamente.
        ///{0}.
        /// </summary>
        internal static string RemoteUserProvider_ValidateUserFaultException {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateUserFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um error desconhecido na autenticação e não foi possível validar os dados do usuário..
        /// </summary>
        internal static string RemoteUserProvider_ValidateUserUnknownError {
            get {
                return ResourceManager.GetString("RemoteUserProvider_ValidateUserUnknownError", resourceCulture);
            }
        }
    }
}
